mpu6050publisher:
  ros__parameters:
    calibrate: True
    gyro_range: 0
    accel_range: 0
    dlpf_bandwidth: 2
    gyro_x_offset: 0.0
    gyro_y_offset: 0.0
    gyro_z_offset: 0.0
    accel_x_offset: 0.0
    accel_y_offset: 0.0
    accel_z_offset: 0.0
    frequency: 100
